### ISSUE TITLE
[Pebbles] AggregationError

### ISSUE THREAD

**Issue by ltagliamonte** [sinkingpoint/prometheus-gravel-gateway#12]
Trying to use pebbles with `{clearmode="mean5m"}` and it doesn't seem to work, maybe i'm getting the doc wrong.
To replicate, run the gateway locally and perform:
```
echo '# TYPE value2 gauge
value2{clearmode="mean5m"} 1' | curl --data-binary @- localhost:4278/metrics/job/lttest
```
this POST will successfully complete, by perform a GET /metrics we get:
```
# TYPE value2 gauge
value2{job="lttest"} 0
```

let's now trying to push another value for the same gauge metric:
```
echo '# TYPE value2 gauge
value2{clearmode="mean5m"} 10' | curl --data-binary @- localhost:4278/metrics/job/lttest
```
will receive the following error:
```
Unhandled rejection: AggregationError(Error("invalid push - new push has different label names than the existing family"))
```

**Comment by sinkingpoint** [comment]
Derp. This was a regression from me de-cloudflarifying things. Fixed - thanks for the report
