### ISSUE TITLE
[Questions] Clustering 

### ISSUE THREAD

**Issue by ltagliamonte-dd** [sinkingpoint/prometheus-gravel-gateway#13]
Hello @sinkingpoint, i'd like to ask few questions about clustering:
- is this feature using any membership algorithm (like serf for example) so that if a node of the cluster is down the metric gets re-assigned to another node?
- is the metric proxy best effort? If a node is down or temp unavailable the data point just discarded?
- can the cluster be scaled in-out? is the data re-organized when this happens?

From what i'm reading the current clustering feature is just best-effort and depending on the requirements not production ready?

**Comment by sinkingpoint** [comment]
> is this feature using any membership algorithm (like serf for example) so that if a node of the cluster is down the metric gets re-assigned to another node?

No

> is the metric proxy best effort? If a node is down or temp unavailable the data point just discarded?

Yes

> can the cluster be scaled in-out? is the data re-organized when this happens?

Yes, with some caveats. Currently we use a hash ring to decide which metrics push goes where. This means that if a node leaves and comes back then metrics will be assigned correct, and scaling out will in theory balance properly

> From what i'm reading the current clustering feature is just best-effort and depending on the requirements not production ready?

Correct
