### ISSUE TITLE
Base64 encode the authorization header

### ISSUE THREAD

**Issue by rene84** [sinkingpoint/prometheus-gravel-gateway#16]
I understand the comment and intention here:

> You'll note that we don't base64 the authorization header, so it's not technically Basic Auth, but I don't like Base64ing it because I believe that gives a false sense of security. Instead, you should enable TLS

However, the basic auth spec themselves mention that base64 has nothing to do with security and should be used in conjuction with TLS https://www.rfc-editor.org/rfc/rfc7617#section-1

The downside of not following the spec is integration efforts with libraries. For example, I want to use prom-client to push to gravel gateway but now I can't use the methods meant for that because they will obviously base64 the authorization header for me.

I would request the change to expect a base64 encoded authorization header to improve client integration. Or maybe just accept both ways for backwards compatibility

**Comment by sinkingpoint** [comment]
Yeah, that was mostly selfish of me. I've just published v1.6.0 that handles both, so that we don't break existing stuff - wanna check it out?
