### ISSUE TITLE
Why is there a TODO for prometheus distributions summaries?

### ISSUE THREAD

**Issue by lhess** [sinkingpoint/prometheus-gravel-gateway#18]
While trying out the gravel gateway, I noticed that the aggregation of [distribution summaries is not supported](https://github.com/sinkingpoint/prometheus-gravel-gateway/blob/master/src/aggregator.rs#L263). I stumbled over this while using distribution summaries.

May I ask what was the reason for not implementing it? Maybe I can help here :)

Thanks a lot!

PS: For now, this detail is maybe worth to be mentioned in the readme.

**Comment by lhess** [comment]
Just found this: https://github.com/weaveworks/prom-aggregation-gateway/blob/master/cmd/prom-aggregation-gateway/main.go#L121

Although I am still wondering why it is not possible to merge summaries...

**Comment by lhess** [comment]
I think this issue can be closed: https://prometheus.io/docs/practices/histograms/#errors-of-quantile-estimation

**Comment by sinkingpoint** [comment]
Correct - there's no real logical way to merge individual summaries together. That behing said, we can improve the errors under this issue. It's not great to just throw a todo
