### ISSUE TITLE
Error when dealing with metrics that only contain HELP and TYPE lines

### ISSUE THREAD

**Issue by kdeberk** [sinkingpoint/prometheus-gravel-gateway#29]
Some metric-pushing clients can generate metrics with `HELP` and `TYPE` lines, but without the actual metric value lines.

For example:
```
# HELP number_of_transactions_total Number of transactions
# TYPE number_of_transactions_total counter
<empty line>
```

When the client tries to push those metrics to the prometheus-gravel-gateway, the push will fail with the error `invalid push - new push has different label names than the existing family`. There are two scenarios where this error is currently thrown where I think the gravel gateway should actually accept the push:

1. the first push did mention a value for the metric along with labels, but a later one didn't:
```
# HELP number_of_transactions_total Number of transactions
# TYPE number_of_transactions_total counter
number_of_transactions_total{label="value"} 1
```
followed by:
```
# HELP number_of_transactions_total Number of transactions
# TYPE number_of_transactions_total counter
```

2. The first push didn't mention a value nor labels, but a later one didn't:
```
# HELP number_of_transactions_total Number of transactions
# TYPE number_of_transactions_total counter
```
followed by:
```
# HELP number_of_transactions_total Number of transactions
# TYPE number_of_transactions_total counter
number_of_transactions_total{label="value"} 1
```

What the gravel-gateway can do for these scenarios is as follows:
1. Don't merge the new family with the older one; the `merge` function returns early.
2. Replace the old family with the new family, the same as if the `should_clear_family` condition in the `merge` function.

**Comment by sinkingpoint** [comment]
This should be fixed in 1.7.0
