### ISSUE TITLE
Error 500 when pushing same metric with different label

### ISSUE THREAD

**Issue by callmesangio** [sinkingpoint/prometheus-gravel-gateway#3]
Hi,

thanks for developing Gravel Gateway!

I have an issue in pushing the same metric with different label values.
I'm not sure whether it's something I'm missing, but here's how to reproduce:

- clone master@06e50df0210797b47a7ca13ccf8fb0f4b8bc159e
- `cargo run` (rustc 1.57.0 (f1edd0429 2021-11-29))
- The following curl returns correctly with 200 OK
```
echo '# HELP mymetric My Metric
> # TYPE mymetric gauge
> mymetric{clearmode="aggregate",label="value1",job="my_metric"} 1.0' | curl -v -H 'Authorization: x' --data-binary @- localhost:4278/metrics
```
- Multiple curl invocations as above yield the expected results (summed values for the metric).
- But the following curl returns with 500 with message `Unhandled rejection: AggregationError(ParseError(InvalidMetric("Cannot add a sample with 3 labels into a family with 2")))*` (see `label="value2"`)
```
echo '# HELP mymetric My Metric
> # TYPE mymetric gauge
> mymetric{clearmode="aggregate",label="value2",job="my_metric"} 1.0' | curl -v -H 'Authorization: x' --data-binary @- localhost:4278/metrics
```

Is this something to be expected?

Please let me know if I can be of further help.

Thanks!

**Comment by sinkingpoint** [comment]
Hi there! Thanks for the report - this is unexpected. I'll get a fix out today

**Comment by sinkingpoint** [comment]
Cut 1.1.2 to address this

**Comment by callmesangio** [comment]
1.1.2 works as expected, thanks for the fast response!
