### ISSUE TITLE
Found some unsupported items

### ISSUE THREAD

**Issue by ixvick** [sinkingpoint/prometheus-gravel-gateway#5]
Found some unsupported items
example:
```
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 9.4094392E12


# Service=myapp, date=Fri May 27 11:34:23 UTC 2022
```

1. coma at the end of labels list is unsupported
2. exponent uppercase letter "E" is not supported, but just lowercase "e"
3. 2 and more blank lines after the last metric is not supported

**Comment by sinkingpoint** [comment]
Interesting... Thanks for the report. The specification of the text exposition format is annoyingly light on these sort of things and so our parser defaults to the more strict OpenMetrics stuff. I'll take a look though - we should attempt to retain compatibility with the Prometheus upstream when possible
